config/routes.rb
Rails.application.routes.draw do
  root 'web_pages#index'
  resources :web_pages do
    member do
      get :words
      get :compare
      get :one_result
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/web_page.rb
class WebPage < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/web_pages_controller.rb
class WebPagesController < ApplicationController
  before_action :set_web_page, only: %i[ show edit update destroy words compare one_result]

  # GET /web_pages or /web_pages.json
  def index
    @web_pages = WebPage.all
  end

  # GET /web_pages/1 or /web_pages/1.json
  def show
  end

  # GET /web_pages/new
  def new
    @web_page = WebPage.new
  end

  # GET /web_pages/1/edit
  def edit
  end

  # POST /web_pages or /web_pages.json
  def create
    @web_page = WebPage.new(web_page_params)

    respond_to do |format|
      if @web_page.save
        format.html { redirect_to @web_page, notice: "Web page was successfully created." }
        format.json { render :show, status: :created, location: @web_page }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @web_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /web_pages/1 or /web_pages/1.json
  def update
    respond_to do |format|
      if @web_page.update(web_page_params)
        if request.referrer.split("/").last == "compare"
          format.html { redirect_to one_result_web_page_path(@web_page), notice: "Web page was successfully updated." }
          format.json { render :show, status: :ok, location: @web_page }
        else
          format.html { redirect_to @web_page, notice: "Web page was successfully updated." }
          format.json { render :show, status: :ok, location: @web_page }
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @web_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /web_pages/1 or /web_pages/1.json
  def destroy
    @web_page.destroy
    respond_to do |format|
      format.html { redirect_to web_pages_url, notice: "Web page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def compare
  end

  def words
    require 'open-uri'
    @doc = Nokogiri::HTML.parse(open("#{@web_page.comparing_url}"){|io| io.read.encode("UTF-8")})
    removed_tags = remove_tags(@doc.text)
    parsed_string = parse_string(removed_tags)
    @words = count_words(parsed_string)
    if has_keywords_tags?(@doc)
      @keywords = get_data_from_meta_tags(@doc, @words)
    else
      @keywords = @words[0..9]
    end
    @count_of_words = 0
    @words.each {|word| @count_of_words += word[1] }
  end

  def one_result
    require 'open-uri'
    @doc1 = Nokogiri::HTML.parse(open("#{@web_page.comparing_url}"){|io| io.read.encode("UTF-8")})
    @doc2 = Nokogiri::HTML.parse(open("#{@web_page.compared_url}"){|io| io.read.encode("UTF-8")})
    @has_metas1 = has_keywords_tags?(@doc1)
    @has_metas2 = has_keywords_tags?(@doc2)
    if has_keywords_tags?(@doc1) && has_keywords_tags?(@doc2)
      removed_tags1 = remove_tags(@doc1.text)
      parsed_string1 = parse_string(removed_tags1)
      @words_counted1 = count_words(parsed_string1)
      @meta1 = get_data_from_meta_tags(@doc1,@words_counted1)   
  
      
      removed_tags2 = remove_tags(@doc2.text)
      parsed_string2 = parse_string(removed_tags2)
      @words_counted2 = count_words(parsed_string2)
      @meta2 = get_data_from_meta_tags(@doc2,@words_counted2)



    elsif has_keywords_tags?(@doc1) || has_keywords_tags?(@doc2)
      if has_keywords_tags?(@doc1)
        removed_tags1 = remove_tags(@doc1.text)
        parsed_string1 = parse_string(removed_tags1)
        @words_counted1 = count_words(parsed_string1)
        @meta1 = get_data_from_meta_tags(@doc1,@words_counted1)

        removed_tags2 = remove_tags(@doc2.text)
        parsed_string2 = parse_string(removed_tags2)
        @words_counted2 = count_words(parsed_string2)
        @meta2 = @words_counted2[0..9]

      else

        removed_tags1 = remove_tags(@doc1.text)
        parsed_string1 = parse_string(removed_tags1)
        @words_counted1 = count_words(parsed_string1)
        @meta1 = @words_counted1[0..9]
        
        removed_tags2 = remove_tags(@doc2.text)
        parsed_string2 = parse_string(removed_tags2)
        @words_counted2 = count_words(parsed_string2)
        @meta2 = get_data_from_meta_tags(@doc2,@words_counted2)

      end

    else

      removed_tags1 = remove_tags(@doc1.text)
      parsed_string1 = parse_string(removed_tags1)
      @words_counted1 = count_words(parsed_string1)
      @meta1 = @words_counted1[0..9]  
  
      
      removed_tags2 = remove_tags(@doc2.text)
      parsed_string2 = parse_string(removed_tags2)
      @words_counted2 = count_words(parsed_string2)
      @meta2 = @words_counted2[0..9]

    end
    @score = calc_score(parsed_string2.count, @meta1[0..9].map{|a| a[0] }, @words_counted2)
  end

  private

    #w2 is the number of words in set 2, meta is the array of keyword and frequency key, value pairs 
    def calc_score(w2, meta1, words_counted_2)
      score = 0
      
      if meta1.length == 10
        meta1[0..2].each{|word1| score += (words_counted_2.map{|kv2| kv2[0] == word1 ? kv2[1] : 0 }.sum * 10) }
        meta1[3..6].each{|word1| score += (words_counted_2.map{|kv2| kv2[0] == word1 ? kv2[1] : 0 }.sum * 5)}
        meta1[7..9].each{|word1| score += (words_counted_2.map{|kv2| kv2[0] == word1 ? kv2[1] : 0 }.sum * 1) }
      else
        meta1.each{|word1| score += (words_counted_2.map{|kv2| kv2[0] == word1 ? kv2[1] : 0 }.sum * 10) }
      end

      score = score.to_f/w2
      score *= 100
    end

    def forbidden_words_to_text
      require 'open-uri'
        doc = Nokogiri::HTML.parse(open("https://www.turkceogretimi.com/tavsiyeler/en-%C3%A7ok-kullan%C4%B1lan-1000-t%C3%BCrk%C3%A7e-kelime"))
        words = []
        doc.xpath("//td").each_with_index do |a,index|
          if index % 3 != 1 && index > 9
          a.text.remove("\n", "\r", /[[:punct:]]/).downcase.split(" ").each {|word| words << word}
          end
         end
        File.open("forbidden_words.txt", "w+") do |f|
          words.each do |word|
            f.write("#{word}, ")
          end
        end
    end

    def forbidden_words
      File.read("forbidden_words.txt").split(", ")
    end


    def has_keywords_tags?(doc)
      !(doc.xpath("//meta[@name='keywords']").blank?)
    end

    def get_data_from_meta_tags(doc, words)
      word_set = doc.xpath("//meta[@name='keywords']").first.values[1].split(",")
      keywords = []
      unless word_set.blank?
        word_set.map{|word| word.split(" ").map{|w| [w.downcase, words.flatten.include?(w.downcase) ? words.select{|c,f| c.downcase == w.downcase }[0][1] : 0]}.each {|kv| keywords << kv}}
      end
      keywords.uniq.sort{|a,b| a[1] <=> b[1]}.reverse.reject{|kv| kv[0].length <4 || kv[0].length >14 || kv[1] < 2 }
    end

    def remove_tags(str)
      removed_tags = ActionView::Base.full_sanitizer.sanitize(str)
      removed_tags
    end

    def parse_string(str)
      parsed_string = []
      forbidden = forbidden_words
      str.remove( /[[:punct:]]/, /\d/, /\d$/ ).split(" ").reject{|e| e.blank? || e.length < 4 || e.length > 15 || e.match(/tag$/) || e.match(/^google/) || e.match(/content$/) || e.match(/header$/) || e.match(/^header/) }.each do  |a|
        unless forbidden.include?(a.downcase)
          parsed_string << a.downcase
        end
      end
      parsed_string
    end

    def count_words(parsed_string)
      words = Hash.new(0)
      parsed_string.each { |iterator| words[iterator] += 1 }
      array_words = words.to_a.sort{|a,b| a[1] <=> b[1]}.reverse
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_web_page
      @web_page = WebPage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def web_page_params
      params.require(:web_page).permit(:comparing_url, :compared_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/web_pages_helper.rb
module WebPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YazLab1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/web_pages/_form.html.erb
<%= simple_form_for( @web_page) do |f| %>
  <% if web_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(web_page.errors.count, "error") %> prohibited this web_page from being saved:</h2>

      <ul>
        <% web_page.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.input :comparing_url, as: :url, label: "*Url" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/web_pages/compare.html.erb
<%= simple_form_for(@web_page)  do |f|%>

  <%= f.input :compared_url, as: :url %>
  <%= f.submit  %>

<% end %>

app/views/web_pages/edit.html.erb
<h1>Editing Web Page</h1>

<%= render 'form', web_page: @web_page %>

<%= link_to 'Show', @web_page %> |
<%= link_to 'Back', web_pages_path %>

app/views/web_pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Web Pages</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @web_pages.each do |web_page| %>
      <tr>
        <td><%= web_page.comparing_url %></td>
        <td><%= link_to 'Show', web_page %></td>
        <td><%= link_to 'Edit', edit_web_page_path(web_page) %></td>
        <td><%= link_to 'Destroy', web_page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Web Page', new_web_page_path %>

app/views/web_pages/new.html.erb
<h1>New Web Page</h1>

<%= render 'form', web_page: @web_page %>

<%= link_to 'Back', web_pages_path %>

app/views/web_pages/one_result.html.erb
<h1>Score : <%= @score %></h1>

<h2>1ST URL CONTENT</h2>
<ul>
  <% @words_counted1.each do |word| %>
  <li><b><%= word[0] %>:</b> <%= word[1] %></li>
  <br>
  <% end %>
</ul>
<h2>Keywords 1</h2>
<ul>
  <% @meta1.each do  |word| %>      
    <li><b><%= word[0].downcase %> : </b> <%= word[1] %>
    <br>
  <% end %>
</ul>

<hr>

<h2>2ND URL CONTENT</h2>
<ul>
  <% @words_counted2.each do |word| %>
  <li><b><%= word[0] %>:</b> <%= word[1] %></li>
  <br>
  <% end %>
</ul>


<h2>Keywords 2</h2>
<ul>
  <% @meta2.each do  |word| %>      
    <li><b><%= word[0].downcase %> : </b> <%= word[1] %>
    <br>
  <% end %>
</ul>

app/views/web_pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @web_page.comparing_url %>
</p>
<%= link_to "Show Frequencies", words_web_page_path(@web_page) %>
<%= link_to 'Edit', edit_web_page_path(@web_page) %> |
<%= link_to 'Back', web_pages_path %>

app/views/web_pages/words.html.erb
<h1>Words From Page</h1>
<h2>Number Of Words: <%= @count_of_words %></h2>
<%= link_to "Compare Another Page", compare_web_page_path(@web_page) %>
<div style="width: 10% important!;">
  <ul>
    <% @words.each do  |word| %>      
        <li><b><%= word[0] %>:</b> <%= word[1] %></li>
      <br>
    <% end %>
  </ul>
</div>

<div style="width: 10% important!;">
  <h1>Keywords</h1>
    <ul>
      <% @keywords.each do  |word| %>      
          <li><b><%= word[0].downcase %> : </b> <%= word[1] %>
            <br>
        <br>
      <% end %>
    </ul>
</div>